# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.define 'control' do |node|
    node.vm.network "private_network", ip: '192.168.0.8', virtualbox__intnet: true, hostname: true
    node.vm.hostname = 'control'
      
    node.vm.provider :virtualbox do |vbox|
      vbox.customize ["modifyvm", :id, "--memory", '1024']
      vbox.customize ["modifyvm", :id, "--cpus", "1"]
    end
  end
    
  config.vm.define 'minion' do |node|
    node.vm.network "private_network", ip: '192.168.0.9', virtualbox__intnet: true, hostname: true
    node.vm.hostname = 'minion'
          
    node.vm.provider :virtualbox do |vbox|
      vbox.customize ["modifyvm", :id, "--memory", '1024']
      vbox.customize ["modifyvm", :id, "--cpus", "1"]
    end    
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "tests/test.yml"
    ansible.become = true
    ansible.groups = {
        "master" => ["control"]
    }
  end
  
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
end
